apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: sjm-test-tas-python-2
  janus-idp.io/tekton: sjm-test-tas-python-2
  backstage.io/kubernetes-id: sjm-test-tas-python-2
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: sjm-test-tas-python-2
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
