apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: sjm-test-tas-python-2
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: sjm-test-tas-python-2 
  name: sjm-test-tas-python-2
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: sjm-test-tas-python-2 
